DROP TABLE IF EXISTS INVOICES;

CREATE TABLE INVOICES (
    ID VARCHAR2 (25) PRIMARY KEY,
    NAME VARCHAR2(100),
    DESCRIPTION VARCHAR2(1000),
    PAID BOOLEAN(1) NOT NULL,
    CONSTRAINT ID_LENGTH CHECK (length(ID) >= 10)
);
